import type { Service } from "./types";
const cutNote = 'Kam- och saxklippning kan medföra pristillägg. Slutpris och lediga tider visas hos Bokadirekt.';
export const services: Service[] = [
    { slug: 'harklippning', title: 'Hårklippning', category: 'Hår', price: 300, from: true, image: '/images/Harklippning.png', intro: 'Ren form. Skarpa linjer. En klippning som känns som du.', details: ['Klippning utifrån din hårtyp och dina önskemål.', 'Klassisk form eller modern fade.', 'Avslutande styling.'], note: cutNote },
    { slug: 'skagg', title: 'Skägg & rakning', category: 'Skägg & kombi', price: 280, from: true, image: '/images/Skagg-rakning.png', intro: 'Det sitter i detaljerna. Forma, trimma och ge skägget en tydlig linje.', details: ['Skäggtrimning.', 'Form som följer dina ansiktsdrag.', 'En välvårdad finish.'] },
    { slug: 'har-och-skagg', title: 'Hår & skägg', category: 'Skägg & kombi', price: 500, from: true, image: '/images/Har-skagg.png', intro: 'En genomtänkt helhet. Från första klippet till sista detaljen.', details: ['Professionell hårklippning.', 'Formning och trimning av skägget.', 'Avslutande styling.'], note: cutNote },
    { slug: 'lyxpaket', title: 'The full treatment', category: 'The luxury edit', price: 890, from: true, image: '/images/The-full-treatment.png', intro: 'Tid för dig. Vårt lyxpaket för hår och skägg.', details: ['Hårklippning och styling.', 'Skäggbehandling med varm handduk.', 'Trimning, formning och vårdande produkter.', 'Avslutande ansiktsmassage.'] },
    { slug: 'studentklippning', title: 'Studentklippning', category: 'Hår', price: 240, from: true, image: '/images/Studentklippning.png', intro: 'En nyklippt känsla, med studentpris.', details: ['Hårklippning och styling.', 'Giltigt studentkort krävs.'], note: cutNote },
    { slug: 'seniorklippning', title: 'Seniorklippning', category: 'Hår', price: 275, from: false, image: '/images/Seniorklippning.png', intro: 'Klassiskt hantverk och en stil som passar dig.', details: ['Klippning för seniorer.', 'Avslutande styling.'], note: cutNote },
    { slug: 'barnklippning', title: 'Barnklippning', category: 'Hår', price: 275, from: true, image: '/images/Barnklippning.png', intro: 'En trygg stund i stolen. En frisyr att trivas med.', details: ['Klippning anpassad efter barnets önskemål.', 'Lugn och personlig service.'], note: cutNote },
    { slug: 'student-har-skagg', title: 'Student · hår & skägg', category: 'Skägg & kombi', price: 400, from: true, image: '/images/Student-har-skagg.png', intro: 'Hår och skägg i en och samma bokning.', details: ['Klippning och skäggtrimning.', 'Giltigt studentkort krävs.'], note: cutNote },
    { slug: 'lyxig-harklippning', title: 'Lyxig hårklippning', category: 'The luxury edit', price: 499, from: true, image: '/images/Harklippning.png', intro: 'Lite mer tid. Lite mer omsorg om helheten.', details: ['Konsultation.', 'Anpassad hårklippning.', 'Styling med kvalitetsprodukter.'] },
    { slug: 'lyxig-skaggbehandling', title: 'Lyxig skäggbehandling', category: 'The luxury edit', price: 399, from: false, image: '/images/Lyxig-skaggbehandling.png', intro: 'Varm handduk. Vårdande oljor. En skarp avslutning.', details: ['Varm handduk och vårdande oljor.', 'Formning och trimning.', 'Återfuktande produkter och avslutande massage.'] },
    { slug: 'hartvatt-styling', title: 'Hårtvätt & styling', category: 'Tillval', price: 129, from: true, image: '/images/Hartvatt-styling.png', intro: 'En uppfräschning mellan klippningarna.', details: ['Hårtvätt.', 'Styling.'] },
    { slug: 'ansiktsbehandling', title: 'Ansiktsbehandling', category: 'Tillval', price: 399, from: false, image: '/images/Ansiktsbehandling.png', intro: 'En stund för huden.', details: ['Rengöring och återfuktning.', 'Behandlingen anpassas efter dina behov.'] },
    { slug: 'tradning-vaxning', title: 'Trådning & vaxning', category: 'Tillval', price: 150, from: false, image: '/images/Tradning-vaxning.png', intro: 'Små detaljer som gör helheten.', details: ['Öron, näsa eller ansikte.', 'Välj område vid bokningen.'] }
];
export const categories = ['Alla', 'Hår', 'Skägg & kombi', 'The luxury edit', 'Tillval'];
export function priceLabel(service: Service) { return `${service.from ? 'Från ' : ''}${service.price} kr`; }
